Repository the-brigadee/Reciholic, pull requests merged in 2022-07, with the labels that each got.

#37 Errors handling for empty strings in recipe backend
  capstone-api/models/recipe.js
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.css
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
Labels: enhancement, backend

#40 connected userProfilePage to the backend, added some minor bug fixes
  capstone-api/models/user.js
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/RecipeCard/RecipeCard.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: bug, frontend

#45 added user profile forms and useStates to connect to the backend
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
Labels: frontend

#50 added user-persistence functionality
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/Navbar/Navbar.jsx
Labels: frontend

#52 Worked on saving recipes backend
  capstone-api/models/savedrecipe.js
  capstone-api/routes/savedrecipe.js
  capstone-ui/src/Components/Navbar/Navbar.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: enhancement, backend

#53 Follow
  capstone-api/app.js
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.css
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.jsx
  capstone-ui/src/Components/UserSearchPage/UserSearchPage.css
  capstone-ui/src/Services/ApiClient.js
Labels: frontend, backend

#55 updating user's profile functionality and minor bug fixes
  capstone-api/models/user.js
  capstone-api/routes/auth.js
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/LandingPage/LandingPage.jsx
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Contexts/authNav.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: bug, frontend, backend

#56 Setup saving functionality
  capstone-api/models/savedrecipe.js
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: enhancement, frontend, backend

#58 Connected Backend deleting functionality with Frontend
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: enhancement, frontend, backend

#61 Add all routes for Mealplanning in Auth and implemented working butto…
  capstone-api/routes/mealplanner.js
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.css
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/Navbar/Navbar.css
  capstone-ui/src/Components/Navbar/Navbar.jsx
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
  capstone-ui/src/Contexts/authNav.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: enhancement, frontend, backend

#62 User profile page
  capstone-api/models/user.js
  capstone-api/package-lock.json
  capstone-api/package.json
  capstone-ui/package-lock.json
  capstone-ui/package.json
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: bug, frontend, backend

#63 Userdetails
  capstone-api/app.js
  capstone-api/models/profile.js
  capstone-api/models/recipe.js
  capstone-api/models/search.js
  capstone-api/routes/profile.js
  capstone-api/routes/search.js
  capstone-ui/src/Assets/imageurls.txt
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/ProfileRecipeCard/ProfileRecipeCard.css
  capstone-ui/src/Components/ProfileRecipeCard/ProfileRecipeCard.jsx
  capstone-ui/src/Components/RecipeCard/RecipeCard.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.css
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.jsx
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.css
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.jsx
  capstone-ui/src/Components/UserSearchGrid/UserSearchGrid.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: bug, frontend, backend

#64 fully functional following and followers feed
  capstone-api/models/profile.js
  capstone-api/routes/follow.js
  capstone-api/routes/profile.js
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/FollowPage/FollowPage.css
  capstone-ui/src/Components/FollowPage/FollowPage.jsx
  capstone-ui/src/Components/ResultPage/ResultPage.jsx
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.css
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: frontend, backend

#65 Fixed rendering issue in MealPlanner page
  capstone-api/models/mealplanner.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.css
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.css
  capstone-ui/src/Contexts/authNav.jsx
Labels: enhancement, frontend

#66 fixed button issues and default image issues
  capstone-ui/src/Components/ProfileRecipeCard/ProfileRecipeCard.jsx
  capstone-ui/src/Components/RecipeCard/RecipeCard.jsx
  capstone-ui/src/Components/SearchResultCard/SearchResultCard.jsx
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.css
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.jsx
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.css
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.jsx
Labels: bug

#67 Drag and drop
  capstone-api/app.js
  capstone-api/models/user.js
  capstone-api/reciholic-schema.sql
  capstone-ui/src/Components/DragDrop/DragDrop.css
  capstone-ui/src/Components/DragDrop/DragDrop.jsx
  capstone-ui/src/Components/Loading/Loading.css
  capstone-ui/src/Components/Loading/Loading.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Contexts/authNav.jsx
Labels: enhancement, frontend, backend

#69 Bug fixing
  capstone-api/models/user.js
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
Labels: bug, frontend, backend

#70 Bug fixing
  capstone-api/models/user.js
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
Labels: bug

#71 Functionality for Button for add plan in Recipe Details working
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Contexts/authNav.jsx
Labels: documentation, frontend

#74 Confirm popup
  capstone-api/models/user.js
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Contexts/authNav.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: enhancement, frontend, backend

#75 user backend fix for deleting account and confirm popup for resetting…
  capstone-api/models/user.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
Labels: enhancement, frontend, backend

#77 fixed styling on the popup container and fixed logging in redirect
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/Popup/Popup.jsx
Labels: bug

#79 updated meal planner selection and fixed users page bug
  .DS_Store
  capstone-api/models/mealplanner.js
  capstone-api/models/recipe.js
  capstone-api/models/search.js
  capstone-api/routes/mealplanner.js
  capstone-api/routes/search.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/MealPlannerSuggestion/MealPlannerSuggestion.css
  capstone-ui/src/Components/MealPlannerSuggestion/MealPlannerSuggestion.jsx
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/UserSearchPage/UserSearchPage.jsx
  capstone-ui/src/Contexts/authNav.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: bug, frontend, backend

#83 Profile page css
  capstone-api/models/recipe.js
  capstone-api/models/search.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/ResultPage/ResultPage.jsx
  capstone-ui/src/Components/SearchResultCard/SearchResultCard.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
Labels: bug, frontend

#85 Improved user experience on add to ingredients list and add to instru…
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.css
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
Labels: bug, frontend

#88 Shopping list
  capstone-api/models/mealplanner.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.css
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
Labels: enhancement, frontend, backend
