Repository the-brigadee/Reciholic, pull requests merged in 2022-08, with the labels that each got.

#90 modification on the reviews backend to prepare to connect
  capstone-api/models/review.js
  capstone-api/reciholic-schema.sql
  capstone-api/routes/review.js
Labels: backend

#94 Website successfully sends message to user with the ingredients they …
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
Labels: enhancement, frontend

#95 Review styling
  capstone-api/.gitignore
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/ReviewCard/ReviewCard.css
  capstone-ui/src/Components/ReviewCard/ReviewCard.jsx
Labels: enhancement, frontend

#98 Added upload file to add recipe form, empty data handling and styling…
  capstone-ui/package-lock.json
  capstone-ui/package.json
  capstone-ui/src/Components/LandingPage/LandingPage.css
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.css
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
Labels: enhancement, frontend, backend

#99 bug fixes
  capstone-api/Procfile
  capstone-api/app.js
  capstone-api/package.json
  capstone-ui/build/200.html
  capstone-ui/build/asset-manifest.json
  capstone-ui/build/index.html
  capstone-ui/build/logo192.png
  capstone-ui/build/logo512.png
  capstone-ui/build/manifest.json
  capstone-ui/build/robots.txt
  capstone-ui/build/static/css/main.d658403c.css
  capstone-ui/build/static/css/main.d658403c.css.map
  capstone-ui/build/static/js/787.cda612ba.chunk.js
  capstone-ui/build/static/js/787.cda612ba.chunk.js.map
  capstone-ui/build/static/js/main.e007ccfc.js
  capstone-ui/build/static/js/main.e007ccfc.js.LICENSE.txt
  capstone-ui/build/static/js/main.e007ccfc.js.map
  capstone-ui/build/static/media/slick.2630a3e3eab21c607e21.svg
  capstone-ui/build/static/media/slick.295183786cd8a1389865.woff
  capstone-ui/build/static/media/slick.a4e97f5a2a64f0ab1323.eot
  capstone-ui/build/static/media/slick.c94f7671dcc99dce43e2.ttf
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/ReviewCard/ReviewCard.jsx
  capstone-ui/src/Services/ApiClient.js
  capstone-ui/src/constants.js
Labels: bug, frontend, backend

#100 Media queries
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
Labels: enhancement

#101 about page
  capstone-ui/src/Assets/Bright.JPG
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/AboutUs/AboutUs.jsx
  capstone-ui/src/Components/Popup/Popup.jsx
Labels: frontend

#102 About page
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/AboutUs/AboutUs.jsx
Labels: frontend

#103 Media queries
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/AboutUs/AboutUs.jsx
  capstone-ui/src/Components/MealPlanner/MealPlanner.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
Labels: frontend

#104 style style more style
  capstone-ui/.gitignore
  capstone-ui/build/200.html
  capstone-ui/build/asset-manifest.json
  capstone-ui/build/index.html
  capstone-ui/build/logo192.png
  capstone-ui/build/logo512.png
  capstone-ui/build/manifest.json
  capstone-ui/build/robots.txt
  capstone-ui/build/static/css/main.d658403c.css
  capstone-ui/build/static/css/main.d658403c.css.map
  capstone-ui/build/static/js/787.cda612ba.chunk.js
  capstone-ui/build/static/js/787.cda612ba.chunk.js.map
  capstone-ui/build/static/js/main.e007ccfc.js
  capstone-ui/build/static/js/main.e007ccfc.js.LICENSE.txt
  capstone-ui/build/static/js/main.e007ccfc.js.map
  capstone-ui/build/static/media/slick.2630a3e3eab21c607e21.svg
  capstone-ui/build/static/media/slick.295183786cd8a1389865.woff
  capstone-ui/build/static/media/slick.a4e97f5a2a64f0ab1323.eot
  capstone-ui/build/static/media/slick.c94f7671dcc99dce43e2.ttf
  capstone-ui/src/Components/AboutUs/AboutUs.jsx
  capstone-ui/src/Components/App/App.js
  capstone-ui/src/Components/MealPlanner/MealPlanner.css
  capstone-ui/src/Components/MealPlanner/MealPlanner.jsx
  capstone-ui/src/Components/Navbar/Navbar.jsx
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/SearchResultCard/SearchResultCard.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: frontend

#105 increased accessible feature
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
Labels: enhancement

#106 users can see how many times a recipe has been saved if it is greater…
  capstone-api/models/recipe.js
  capstone-api/routes/recipe.js
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Services/ApiClient.js
Labels: enhancement

#107 fixed bug
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
Labels: bug, frontend

#108 Phone query
  capstone-ui/src/Assets/doneCSS.txt
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/App/App.css
  capstone-ui/src/Components/LandingPage/LandingPage.css
  capstone-ui/src/Components/Navbar/Navbar.css
  capstone-ui/src/Components/Navbar/Navbar.jsx
  capstone-ui/src/Components/ProfileRecipeCard/ProfileRecipeCard.css
  capstone-ui/src/Components/RecipeCard/RecipeCard.css
  capstone-ui/src/Components/RecipeGrid/RecipeGrid.css
  capstone-ui/src/Components/ResultPage/ResultPage.css
  capstone-ui/src/Components/SearchResultCard/SearchResultCard.css
  capstone-ui/src/Components/SearchResultGrid/SearchResultGrid.css
  capstone-ui/src/Components/Sidebar/Sidebar.css
  capstone-ui/src/Components/Sidebar/Sidebar.jsx
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.css
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.css
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.css
  capstone-ui/src/Components/UserSearchGrid/UserSearchGrid.css
  capstone-ui/src/Contexts/authNav.jsx
  capstone-ui/src/index.css
Labels: enhancement

#109 Phone query
  capstone-ui/src/Components/CategoryDropdown/CategoryDropdown.jsx
  capstone-ui/src/Components/Navbar/Navbar.css
  capstone-ui/src/Components/Navbar/Navbar.jsx
  capstone-ui/src/Components/RecipeCard/RecipeCard.css
  capstone-ui/src/Components/Sidebar/Sidebar.css
  capstone-ui/src/Components/Sidebar/Sidebar.jsx
Labels: enhancement, frontend

#110 Contact form working
  capstone-api/package-lock.json
  capstone-ui/src/Assets/Anthony.jpg
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/AboutUs/AboutUs.jsx
Labels: frontend

#111 more navbar changes to be responsive
  capstone-ui/src/Assets/doneCSS.txt
  capstone-ui/src/Components/App/App.css
  capstone-ui/src/Components/LandingPage/LandingPage.css
  capstone-ui/src/Components/MealPlanner/MealPlanner.css
  capstone-ui/src/Components/Navbar/Navbar.css
  capstone-ui/src/Components/Navbar/Navbar.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
  capstone-ui/src/Components/SearchResultGrid/SearchResultGrid.jsx
  capstone-ui/src/Components/Sidebar/Sidebar.css
  capstone-ui/src/Components/Sidebar/Sidebar.jsx
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.css
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.jsx
  capstone-ui/src/Components/UserSearchGrid/UserSearchGrid.jsx
Labels: enhancement, frontend

#112 Phone query
  capstone-ui/src/Components/ProfileRecipeCard/ProfileRecipeCard.css
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.css
  capstone-ui/src/Components/RecipeCard/RecipeCard.css
Labels: enhancement

#113 added social links to about page
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/AboutUs/AboutUs.jsx
  capstone-ui/src/Components/SearchResultCard/SearchResultCard.css
  capstone-ui/src/Components/UserSearchCard/UserSearchCard.css
Labels: frontend

#114 factored register form into 2 steps
  capstone-api/models/user.js
  capstone-ui/src/Components/Popup/Popup.css
  capstone-ui/src/Components/Popup/Popup.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.css
Labels: enhancement

#116 Loading components for several pages and functions
  capstone-ui/src/Assets/doneCSS.txt
  capstone-ui/src/Components/AboutUs/AboutUs.css
  capstone-ui/src/Components/App/App.css
  capstone-ui/src/Components/DragDrop/DragDrop.css
  capstone-ui/src/Components/ProfileRecipeCard/ProfileRecipeCard.css
  capstone-ui/src/Components/RecipeCard/RecipeCard.css
  capstone-ui/src/Components/RecipeGrid/RecipeGrid.css
  capstone-ui/src/Components/RecipeGrid/RecipeGrid.jsx
  capstone-ui/src/Components/ResultPage/ResultPage.css
  capstone-ui/src/Components/ResultPage/ResultPage.jsx
  capstone-ui/src/Components/SearchResultCard/SearchResultCard.css
  capstone-ui/src/Components/SearchResultGrid/SearchResultGrid.css
  capstone-ui/src/Components/SearchResultGrid/SearchResultGrid.jsx
  capstone-ui/src/Components/UserDetailPage/UserDetailPage.jsx
  capstone-ui/src/Components/UserProfilePage/UserProfilePage.jsx
  capstone-ui/src/Components/UserSearchGrid/UserSearchGrid.css
  capstone-ui/src/Components/UserSearchGrid/UserSearchGrid.jsx
  capstone-ui/src/Components/UserSearchPage/UserSearchPage.jsx
Labels: enhancement, frontend

#115 fixed autofocus on the meal add page and fixed the save button on the…
  capstone-ui/src/Components/RecipeAddPage/RecipeAdd.jsx
  capstone-ui/src/Components/RecipeDetail/RecipeDetail.jsx
Labels: bug, enhancement
